name = "heroes-aion2-api"
main = "worker.js"
compatibility_date = "2026-09-27"
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "heroes-aion2"
database_id = "338997c2-a431-469b-a634-f6178e2ab67e"

[vars]
SITE_ORIGIN = "https://www.retroart.link"

[[routes]]
pattern = "retroart.link/api/*"
zone_name = "retroart.link"

[[routes]]
pattern = "www.retroart.link/api/*"
zone_name = "retroart.link"
